version: "3.9"
services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: "notebook"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"